name: afternoon build at 15h40

on:
 schedule:
  - cron: '40 15 * * *'

jobs:
 afternoon_build:
   runs-on: window-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0


    - name: Run Unit Tests
      run: mvn test

    - name: Build with Maven
      run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

    - uses: actions/upload-artifact@master
      with:
          name: digibank1.war
          path: ./target/*digitalbank*.war
