name: run unit tests of feature branches

on:
   push:
     branches: 
        'feature/*'

jobs:
   Hello:
      runs-on: 'ubuntu-lastest'

      steps:
         - name: Checkout
           uses: actions/checkout@v4.0.0

         - name: run unit test
           run: mvn test
